version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: catalogue-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: catalogue
    volumes:
      - mongodb_data:/data/db
    networks:
      - catalogue-network

networks:
  catalogue-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local

