version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: catalogue-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    networks:
      - catalogue-network

volumes:
  mongodb_data:

networks:
  catalogue-network:
    driver: bridge
